---
title: "Publications"
output:
  html_document:
    toc: true
    toc_float: true
---
<br>

### 2018

[MetaboDiff: an R package for differential metabolomic analysis](https://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/bty344/4987147)  
**Mock A**, Warta R, Dettling S, Brors B, Jäger D, Herold-Mende C.  
**Bioinformatics.** 2018 Apr 26. doi: 10.1093/bioinformatics/bty344. [Epub ahead of print.]

<br>

[Drug-perturbation-based stratification of blood cancer.](https://www.ncbi.nlm.nih.gov/pubmed/29227286)  
Dietrich S, Oleś M, Lu J, Sellner L, Anders S, Velten B, Wu B, Hüllein J, da Silva Liberio M, Walther T, Wagner L, Rabe S, Ghidelli-Disse S, Bantscheff M, Oleś AK, Słabicki M, **Mock A**, Oakes CC, Wang S, Oppermann S, Lukas M, Kim V, Sill M, Benner A, Jauch A, Sutton LA, Young E, Rosenquist R, Liu X, Jethwa A, Lee KS, Lewis J, Putzker K, Lutz C, Rossi D, Mokhir A, Oellerich T, Zirlik K, Herling M, Nguyen-Khac F, Plass C, Andersson E, Mustjoki S, von Kalle C, Ho AD, Hensel M, Dürig J, Ringshausen I, Zapatka M, Huber W, Zenz T.  
**J Clin Invest.** 2018 Jan 2;128(1):427-445. doi: 10.1172/JCI93801. Epub 2017 Dec 11.

<br>

### 2017

[The 2016 WHO classification of central nervous system tumors: what neurologists need to know](https://www.ncbi.nlm.nih.gov/pubmed/28901970)   
DeWitt JC\*, **Mock A\***, Louis DN.   
**Curr Opin Neurol**. 2017 Dec;30(6):643-649. doi: 10.1097/WCO.0000000000000490.

<br>

[CVE: an R package for interactive variant prioritisation in precision oncology](https://www.ncbi.nlm.nih.gov/pubmed/28545463)    
**Mock A**, Murphy S, Morris J, Marass F, Rosenfeld N, Massie C.  
**BMC Med Genomics**. 2017 May 25;10(1):37. doi: 10.1186/s12920-017-0261-6.

<br>

### 2016

[Spatial transcriptome analysis reveals Notch pathway-associated prognostic markers in IDH1 wild-type glioblastoma involving the subventricular zone](https://www.ncbi.nlm.nih.gov/pubmed/27782828)  
Jungk C, **Mock A**, Exner J, Geisenberger C, Warta R, Capper D, Abdollahi A, Friauf S, Lahrmann B, Grabe N, Beckhove P, von Deimling A, Unterberg A, Herold-Mende C.  
**BMC Med**. 2016 Oct 26;14(1):170.

<br>

[Prognostic value of the extent of resection in supratentorial WHO grade II astrocytomas stratified for IDH1 mutation status: a single-center volumetric analysis.](https://www.ncbi.nlm.nih.gov/pubmed/27344556)  
Jungk C, Scherer M, **Mock A**, Capper D, Radbruch A, von Deimling A, Bendszus M, Herold-Mende C, Unterberg A.  
**J Neurooncol**. 2016 Sep;129(2):319-28. doi: 10.1007/s11060-016-2177-y.

<br>

[Combined Treatment of ATRA with Epigenetic Drugs Increases Aggressiveness of Glioma Xenografts.](https://www.ncbi.nlm.nih.gov/pubmed/27069124)  
Schmoch T, Gal Z, **Mock A**, Mossemann J, Lahrmann B, Grabe N, Schmezer P, Lasitschka F, Beckhove P, Unterberg A, Herold-Mende C.  
**Anticancer Res**. 2016 Apr;36(4):1489-96.

<br>

[LOC283731 promoter hypermethylation prognosticates survival after radiochemotherapy in IDH1 wild-type glioblastoma patients.](https://www.ncbi.nlm.nih.gov/pubmed/26934681)  
**Mock A\***, Geisenberger C\*, Orlik C, Warta R, Schwager C, Jungk C, Dutruel C, Geiselhart L, Weichenhan D, Zucknick M, Nied AK, Friauf S, Exner J, Capper D, Hartmann C, Lahrmann B, Grabe N, Debus J, von Deimling A, Popanda O, Plass C, Unterberg A, Abdollahi A, Schmezer P, Herold-Mende C.      
**Int J Cancer**. 2016 Jul 15;139(2):424-32. doi: 10.1002/ijc.30069. Epub 2016 Mar 18.

<br>

[Transcriptomic analysis of aggressive meningiomas identifies PTTG1 and LEPR as prognostic biomarkers independent of WHO grade.](https://www.ncbi.nlm.nih.gov/pubmed/26894859)  
Schmidt M\*, **Mock A\***, Jungk C, Sahm F, Ull AT, Warta R, Lamszus K, Gousias K, Ketter R, Roesch S, Rapp C, Schefzyk S, Urbschat S, Lahrmann B, Kessler AF, Löhr M, Senft C, Grabe N, Reuss D, Beckhove P, Westphal M, von Deimling A, Unterberg A, Simon M, Herold-Mende C.  
**Oncotarget**. 2016 Mar 22;7(12):14551-68. doi: 10.18632/oncotarget.7396.

<br>

### 2015

[Molecular profiling of long-term survivors identifies a subgroup of glioblastoma characterized by chromosome 19/20 co-gain.](https://www.ncbi.nlm.nih.gov/pubmed/25931051)  
Geisenberger C\*, **Mock A\***, Warta R, Rapp C, Schwager C, Korshunov A, Nied AK, Capper D, Brors B, Jungk C, Jones D, Collins VP, Ichimura K, Bäcklund LM, Schnabel E, Mittelbron M, Lahrmann B, Zheng S, Verhaak RG, Grabe N, Pfister SM, Hartmann C, von Deimling A, Debus J, Unterberg A, Abdollahi A, Herold-Mende C.    
**Acta Neuropathol**. 2015 Sep;130(3):419-34. doi: 10.1007/s00401-015-1427-y. Epub 2015 May 1.

<br>

[Non-invasive glioblastoma immunoprofiling by printed peptide arrays.](https://www.ncbi.nlm.nih.gov/pubmed/27057435)     
**Mock A**, Herold-Mende C.  
**Oncoimmunology**. 2015 Aug 12;5(2):e1069941. eCollection 2016 Feb.

<br>

[Endothelial Cells Derived from Non-malignant Tissues Are of Limited Value as Models for Brain Tumor Vasculature.](https://www.ncbi.nlm.nih.gov/pubmed/25964546)    
Lohr J\*, **Mock A\***, Beckhove P, Herold-Mende C.    
**Anticancer Res**. 2015 May;35(5):2681-90.

<br>

[Printed peptide arrays identify prognostic TNC serumantibodies in glioblastoma patients.](https://www.ncbi.nlm.nih.gov/pubmed/25944688)    
**Mock A**, Warta R, Geisenberger C, Bischoff R, Schulte A, Lamszus K, Stadler V, Felgenhauer T, Schichor C, Schwartz C, Matschke J, Jungk C, Ahmadi R, Sahm F, Capper D, Glass R, Tonn JC, Westphal M, von Deimling A, Unterberg A, Bermejo JL, Herold-Mende C.  
**Oncotarget**. 2015 May 30;6(15):13579-90.

<br>

### 2014

[Microenvironment and brain tumor stem cell maintenance: impact of the niche.](https://www.ncbi.nlm.nih.gov/pubmed/25175691)    
Herold-Mende C, **Mock A**.  
**Anticancer Agents Med Chem**. 2014;14(8):1065-74. Review.

<br>

[Reduced promoter methylation and increased expression of CSPG4 negatively influences survival of HNSCC patients.](https://www.ncbi.nlm.nih.gov/pubmed/24740185)   
Warta R, Herold-Mende C, Chaisaingmongkol J, Popanda O, **Mock A**, Mogler C, Osswald F, Herpel E, Küstner S, Eckstein V, Plass C, Plinkert P, Schmezer P, Dyckhoff G.  
**Int J Cancer**. 2014 Dec 1;135(11):2727-34. doi: 10.1002/ijc.28906. Epub 2014 Apr 26.

<br>

[Lessons we learned from high-throughput and top-down systems biology analyses about glioma stem cells.](https://www.ncbi.nlm.nih.gov/pubmed/23530497)    
**Mock A**, Chiblak S, Herold-Mende C.  
**Curr Pharm Des**. 2014;20(1):66-72. Review.
