---
title: "Hands-on Praktikum: Einführung in die angewandte Datenanalyse mit `R`"
---

#### HeiCuMed | Wahlfachtrack internistische Onkologie, Sozität Czerny & MEDISS Promotionsprogramm 

`Andreas Mock`  
Medizinische Onkologie, Nationales Centrum für Tumorerkrankungen (NCT) Heidelberg

******

**Termine Wintersemester 2018/2019**   
**Ort:** NCT INF 460 Raum K1 1.OG   
**Kurszeiten:** 

- 15.01.2019 - 15:30-17:00 Uhr 
- 05.02.2019 - 15:30-17:00 Uhr
- 12.02.2019 - 15:30-17:00 Uhr

Wie kaum in einem anderen Fach werden in der Onkologie Erkrankungen auf den verschiedensten Ebenen der Biologie mit Hilfe von Hochdurchsatzdaten (Omics) analysiert. Durch diese Präzisionsonkologie erhofft man sich zielgerichtete (Immun-)Therapien entwickeln und einsetzen zu können. Diesen Prozess aktiv als Onkologe zu begleiten ist herausforderend und spannend und wird in zunehmenden Maße verlangen, Datenanalysen zu verstehen und im besten Falle sogar selber durchführen zu können.

In diesem Einführungspraktikum möchte ich die Scheu vor angewandter Datenanalye nehmen und aufzeigen, wie einfach man das große Einmaleins der Datenanalyse- und visualisierung mit der Programmiersprache R erlernen kann. Das Praktikum richtet sich hierbei gezielt an Studierende, Ärzte und Wissenschaftler die bisher wenig oder noch keine Berührungspunkte mit einer Programmiersprache hatten.

**Vorbereitungen**

Bitte die folgenden Programme auf eurem Notebook installieren bzw. einrichten, um am Praktikumstag möglichst viel Zeit der Datenanalyse widmen zu können: 

- Installation von [R](https://www.r-project.org) und [RStudio](https://www.rstudio.com)
- Falls noch nicht vorhanden Einrichten eines [eduroam Zugangs](https://www.urz.uni-heidelberg.de/de/eduroam), um im Kursraum im NCT das Internet nutzen zu können. Wichtig: Angestellte der Uniklinik (Ärzte und Wissenschaftler) benötigen für die Einrichtung des Zertifikates eine Uni-ID, welche über das URZ Heidelberg zu beziehen ist. 
- Bitte eigenes Notebook am Praktikumstag nicht vergessen
- An Tag 3 gibt es die Möglichkeit eigene Datensätze von euch in R zu laden, bitte schon einmal überlegen, welche ihr analysieren möchtet.

**Kursunterlagen Sommersemester 18**   

|Tag 1| Tag 2| Tag 3|
|-------|-------|-------|-------|
|[Präsentation](http://andreasmock.github.io/presentations/pres_day1.pdf)|[Präsentation](http://andreasmock.github.io/presentations/pres_day2.pdf)|[Präsentation](http://andreasmock.github.io/presentations/pres_day3.pdf)|
|Übungen|Übungen|Übungen|
|Lösungen|Lösungen|Lösungen||

Die Lösungen zu den Übungen werden am Ende des jeweiligen Praktikumstags hochgeladen
